eureka:
  instance:
    prefer-ip-address: true
    
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    name: microservice
    password: Abcde12345
    driver-class-name: com.mysql.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8085
  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
